### ISSUE TITLE
barkeep failed to run: DatabaseConnectionError

### ISSUE THREAD

**Issue by weakish** [saadfarooq/docker-images#1]
```
docker pull saadfarooq/barkeep
docker run -d -p 8040:8040 saadfarooq/barkeep
```

Access localhost:8040 get this error:

```
Sequel::DatabaseConnectionError
Mysql2::Error: Unknown MySQL server host 'mysql' (0)
.../gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
.../gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
.../gems/sequel-3.36.1/lib/sequel/adapters/mysql2.rb:49:in `new'
.../gems/sequel-3.36.1/lib/sequel/adapters/mysql2.rb:49:in `connect'
.../gems/sequel-3.36.1/lib/sequel/database/misc.rb:48:in `block in initialize'
.../gems/sequel-3.36.1/lib/sequel/connection_pool.rb:100:in `call'
.../gems/sequel-3.36.1/lib/sequel/connection_pool.rb:100:in `make_new'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:148:in `make_new'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:134:in `available'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:124:in `block in acquire'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:170:in `block in sync'
<internal:prelude>:10:in `synchronize'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:170:in `sync'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:123:in `acquire'
.../gems/sequel-3.36.1/lib/sequel/connection_pool/threaded.rb:95:in `hold'
.../gems/sequel-3.36.1/lib/sequel/database/connecting.rb:229:in `synchronize'
.../gems/sequel-3.36.1/lib/sequel/adapters/shared/mysql_prepared_statements.rb:23:in `execute'
.../gems/sequel-3.36.1/lib/sequel/dataset/actions.rb:744:in `execute'
.../gems/sequel-3.36.1/lib/sequel/adapters/mysql2.rb:171:in `execute'
.../gems/sequel-3.36.1/lib/sequel/adapters/mysql2.rb:147:in `fetch_rows'
.../gems/sequel-3.36.1/lib/sequel/dataset/actions.rb:131:in `each'
.../gems/sequel-3.36.1/lib/sequel/dataset/actions.rb:515:in `single_record'
.../gems/sequel-3.36.1/lib/sequel/dataset/actions.rb:188:in `first'
.../gems/sequel-3.36.1/lib/sequel/model/base.rb:307:in `find'
/usr/src/app/barkeep_server.rb:179:in `block in <class:BarkeepServer>'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `block in compile!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `[]'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `catch'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:777:in `block in filter!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:777:in `each'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:777:in `filter!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:885:in `dispatch!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
.../gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
.../gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
.../gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
.../gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
.../gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
.../gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
.../gems/rack-1.4.1/lib/rack/builder.rb:134:in `call'
.../gems/rack-1.4.1/lib/rack/urlmap.rb:64:in `block in call'
.../gems/rack-1.4.1/lib/rack/urlmap.rb:49:in `each'
.../gems/rack-1.4.1/lib/rack/urlmap.rb:49:in `call'
.../gems/rack-1.4.1/lib/rack/lint.rb:48:in `_call'
.../gems/rack-1.4.1/lib/rack/lint.rb:36:in `call'
.../gems/rack-1.4.1/lib/rack/showexceptions.rb:24:in `call'
.../gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call'
.../gems/rack-1.4.1/lib/rack/chunked.rb:43:in `call'
.../gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
.../gems/unicorn-4.2.1/lib/unicorn/http_server.rb:530:in `process_client'
.../gems/unicorn-4.2.1/lib/unicorn/http_server.rb:604:in `worker_loop'
.../gems/unicorn-4.2.1/lib/unicorn/http_server.rb:487:in `spawn_missing_workers'
.../gems/unicorn-4.2.1/lib/unicorn/http_server.rb:137:in `start'
.../gems/unicorn-4.2.1/bin/unicorn:121:in `<top (required)>'
.../bin/unicorn:16:in `load'
.../bin/unicorn:16:in `<main>'
```

**Comment by weakish** [comment]
Sorry, I should have used docker-compose

**Comment by saadfarooq** [comment]
Great...
